# Generated by carnix 0.9.8: carnix generate-nix --src /home/adfaure/Projects/batsim.rs
{ lib, buildPlatform, buildRustCrate, buildRustCrateHelpers, cratesIO, fetchgit }:
with buildRustCrateHelpers;
let inherit (lib.lists) fold;
    inherit (lib.attrsets) recursiveUpdate;
in
rec {
  crates = cratesIO // rec {
# batsim-rs-0.2.0

    crates.batsim_rs."0.2.0" = deps: { features?(features_.batsim_rs."0.2.0" deps {}) }: buildRustCrate {
      crateName = "batsim-rs";
      version = "0.2.0";
      authors = [ "FAURE Adrien <adrien.faure@protonmail.com>" ];
      src = exclude [ ".git" "target" ] ./.;
      libPath = "src/libbatsim/lib.rs";
      libName = "batsim";
      dependencies = mapFeatures features ([
        (cratesIO.crates."env_logger"."${deps."batsim_rs"."0.2.0"."env_logger"}" deps)
        (cratesIO.crates."log"."${deps."batsim_rs"."0.2.0"."log"}" deps)
        (cratesIO.crates."serde"."${deps."batsim_rs"."0.2.0"."serde"}" deps)
        (cratesIO.crates."serde_derive"."${deps."batsim_rs"."0.2.0"."serde_derive"}" deps)
        (cratesIO.crates."serde_json"."${deps."batsim_rs"."0.2.0"."serde_json"}" deps)
        (cratesIO.crates."zmq"."${deps."batsim_rs"."0.2.0"."zmq"}" deps)
      ]);
    };
    features_.batsim_rs."0.2.0" = deps: f: updateFeatures f (rec {
      batsim_rs."0.2.0".default = (f.batsim_rs."0.2.0".default or true);
      env_logger."${deps.batsim_rs."0.2.0".env_logger}".default = true;
      log."${deps.batsim_rs."0.2.0".log}".default = true;
      serde."${deps.batsim_rs."0.2.0".serde}".default = true;
      serde_derive."${deps.batsim_rs."0.2.0".serde_derive}".default = true;
      serde_json."${deps.batsim_rs."0.2.0".serde_json}".default = true;
      zmq."${deps.batsim_rs."0.2.0".zmq}".default = true;
    }) [
      (cratesIO.features_.env_logger."${deps."batsim_rs"."0.2.0"."env_logger"}" deps)
      (cratesIO.features_.log."${deps."batsim_rs"."0.2.0"."log"}" deps)
      (cratesIO.features_.serde."${deps."batsim_rs"."0.2.0"."serde"}" deps)
      (cratesIO.features_.serde_derive."${deps."batsim_rs"."0.2.0"."serde_derive"}" deps)
      (cratesIO.features_.serde_json."${deps."batsim_rs"."0.2.0"."serde_json"}" deps)
      (cratesIO.features_.zmq."${deps."batsim_rs"."0.2.0"."zmq"}" deps)
    ];


# end

  };

  batsim_rs = crates.crates.batsim_rs."0.2.0" deps;
  __all = [ (batsim_rs {}) ];
  deps.aho_corasick."0.6.10" = {
    memchr = "2.2.0";
  };
  deps.batsim_rs."0.2.0" = {
    env_logger = "0.4.3";
    log = "0.3.9";
    serde = "1.0.91";
    serde_derive = "1.0.91";
    serde_json = "1.0.39";
    zmq = "0.9.0";
  };
  deps.bitflags."0.7.0" = {};
  deps.cfg_if."0.1.9" = {};
  deps.env_logger."0.4.3" = {
    log = "0.3.9";
    regex = "0.2.11";
  };
  deps.error_chain."0.10.0" = {};
  deps.itoa."0.4.4" = {};
  deps.lazy_static."1.3.0" = {};
  deps.libc."0.2.55" = {};
  deps.log."0.3.9" = {
    log = "0.4.6";
  };
  deps.log."0.4.6" = {
    cfg_if = "0.1.9";
  };
  deps.memchr."2.2.0" = {};
  deps.metadeps."1.1.2" = {
    error_chain = "0.10.0";
    pkg_config = "0.3.14";
    toml = "0.2.1";
  };
  deps.pkg_config."0.3.14" = {};
  deps.proc_macro2."0.4.30" = {
    unicode_xid = "0.1.0";
  };
  deps.quote."0.6.12" = {
    proc_macro2 = "0.4.30";
  };
  deps.regex."0.2.11" = {
    aho_corasick = "0.6.10";
    memchr = "2.2.0";
    regex_syntax = "0.5.6";
    thread_local = "0.3.6";
    utf8_ranges = "1.0.2";
  };
  deps.regex_syntax."0.5.6" = {
    ucd_util = "0.1.3";
  };
  deps.ryu."0.2.8" = {};
  deps.serde."1.0.91" = {};
  deps.serde_derive."1.0.91" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    syn = "0.15.34";
  };
  deps.serde_json."1.0.39" = {
    itoa = "0.4.4";
    ryu = "0.2.8";
    serde = "1.0.91";
  };
  deps.syn."0.15.34" = {
    proc_macro2 = "0.4.30";
    quote = "0.6.12";
    unicode_xid = "0.1.0";
  };
  deps.thread_local."0.3.6" = {
    lazy_static = "1.3.0";
  };
  deps.toml."0.2.1" = {};
  deps.ucd_util."0.1.3" = {};
  deps.unicode_xid."0.1.0" = {};
  deps.utf8_ranges."1.0.2" = {};
  deps.zmq."0.9.0" = {
    bitflags = "0.7.0";
    libc = "0.2.55";
    log = "0.4.6";
    zmq_sys = "0.9.0";
  };
  deps.zmq_sys."0.9.0" = {
    libc = "0.2.55";
    metadeps = "1.1.2";
  };
}
